services:
    laravel.test:
        environment:
            VCS_URL: "${CODESPACE_NAME:-local}"
            APP_URL: "https://${CODESPACE_NAME:-localhost}-80.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-githubpreview.dev}"
            ASSET_URL: "https://${CODESPACE_NAME:-localhost}-80.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-githubpreview.dev}"
            VITE_ASSET_URL: "https://${CODESPACE_NAME:-localhost}-5173.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-githubpreview.dev}"
        networks:
            - sail

networks:
    sail:
        driver: bridge
